server:
  port: 33400   # used later by Task Five's /balance check

spring:
  datasource:
    url: jdbc:h2:mem:midasdb;DB_CLOSE_DELAY=-1;MODE=LEGACY
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update   # auto create/update tables for local dev/tests
    open-in-view: false
    show-sql: false

# Topic already set in test resources; adding here for completeness or local runs
general:
  kafka-topic: test-topic
